package no.knubo.accounting.client.views.registers;

public class EmailDefaultStyle {

    public static final String DEFAULT = "" //
            + "{ name : 'Paragraph'       , element : 'p' },\n"
            + "{ name : 'Heading 1'       , element : 'h1' },\n"
            + "{ name : 'Heading 2'       , element : 'h2' },\n"
            + "{ name : 'Heading 3'       , element : 'h3' },\n"
            + "{ name : 'Heading 4'       , element : 'h4' },\n"
            + "{ name : 'Heading 5'       , element : 'h5' },\n"
            + "{ name : 'Heading 6'       , element : 'h6' },\n"
            + "{ name : 'Preformatted Text', element : 'pre' },\n"
            + "{ name : 'Address'         , element : 'address' },\n"
            + "\n"
            + "{ name : 'Blue Title'      , element : 'h3', styles : { 'color' : 'Blue' } },\n"
            + "{ name : 'Red Title'       , element : 'h3', styles : { 'color' : 'Red' } },\n"
            + "\n"
            + "{ name : 'Strong'          , element : 'strong', overrides : 'b' },\n"
            + "{ name : 'Emphasis'            , element : 'em'    , overrides : 'i' },\n"
            + "{ name : 'Underline'       , element : 'u' },\n"
            + "{ name : 'Strikethrough'   , element : 'strike' },\n"
            + "{ name : 'Subscript'       , element : 'sub' },\n"
            + "{ name : 'Superscript'     , element : 'sup' },\n"
            + "\n"
            + "{ name : 'Marker: Yellow'  , element : 'span', styles : { 'background-color' : 'Yellow' } },\n"
            + "{ name : 'Marker: Green'   , element : 'span', styles : { 'background-color' : 'Lime' } },\n"
            + "\n"
            + "{ name : 'Big'             , element : 'big' },\n"
            + "{ name : 'Small'           , element : 'small' },\n"
            + "{ name : 'Typewriter'      , element : 'tt' },\n"
            + "\n"
            + "{ name : 'Computer Code'   , element : 'code' },\n"
            + "{ name : 'Keyboard Phrase' , element : 'kbd' },\n"
            + "{ name : 'Sample Text'     , element : 'samp' },\n"
            + "{ name : 'Variable'            , element : 'var' },\n"
            + "\n"
            + "{ name : 'Deleted Text'        , element : 'del' },\n"
            + "{ name : 'Inserted Text'   , element : 'ins' },\n"
            + "\n"
            + "{ name : 'Cited Work'      , element : 'cite' },\n"
            + "{ name : 'Inline Quotation'    , element : 'q' },\n"
            + "\n"
            + "{ name : 'Language: RTL'   , element : 'span', attributes : { 'dir' : 'rtl' } },\n"
            + "{ name : 'Language: LTR'   , element : 'span', attributes : { 'dir' : 'ltr' } },\n"
            + "\n"
            + "\n"
            + "{\n"
            + "   name : 'Image on Left',\n"
            + "   element : 'img',\n"
            + "   attributes :\n"
            + "   {\n"
            + "       'style' : 'padding: 5px; margin-right: 5px',\n"
            + "       'border' : '2',\n"
            + "       'align' : 'left'\n"
            + "   }\n"
            + "},\n"
            + "\n"
            + "{\n"
            + "   name : 'Image on Right',\n"
            + "   element : 'img',\n"
            + "   attributes :\n"
            + "   {\n"
            + "       'style' : 'padding: 5px; margin-left: 5px',\n"
            + "       'border' : '2',\n"
            + "       'align' : 'right'\n"
            + "   }\n"
            + "},\n"
            + "\n"
            + "{ name : 'Borderless Table', element : 'table', styles: { 'border-style': 'hidden', 'background-color' : '#E6E6FA' } },\n"
            + "{ name : 'Square Bulleted List', element : 'ul', styles : { 'list-style-type' : 'square' } }\n" + // 
            "";

}
