#!/bin/sh
APPDIR=`dirname $0`;
GWT_ROOT='/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.4.10'
CP="$APPDIR/src:$APPDIR/bin:$GWT_ROOT/gwt-user.jar:$GWT_ROOT/gwt-dev-mac.jar"

java -XstartOnFirstThread -cp "$CP" com.google.gwt.dev.GWTShell -noserver -out "$APPDIR/www" "$@" RegnskapClient/www/no.knubo.accounting.AccountingGWT/AccountingGWT.html;
