#!/bin/sh
APPDIR=`dirname $0`;
GWT_ROOT='/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.4.61'
CP="$APPDIR/src:$APPDIR/bin:$GWT_ROOT/gwt-user.jar:$GWT_ROOT/gwt-dev-mac.jar"
java -cp "$CP" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src no.knubo.accounting.client.Elements;
sed 's/client.Constants/client.ConstantsWithLookup/g' <src/no/knubo/accounting/client/Elements.java > src/no/knubo/accounting/client/Elements.fix
mv src/no/knubo/accounting/client/Elements.fix src/no/knubo/accounting/client/Elements.java
