package no.knubo.accounting.client.misc;

public enum WidgetIds {
    LINE_EDIT_VIEW, REGISTER_MEMBERSHIP, SETTINGS, ADD_PERSON, SHOW_MONTH, SHOW_MEMBERS, FIND_PERSON
            , SHOW_CLASS_MEMBERS, SHOW_TRAINING_MEMBERS, ABOUT, REGISTER_HAPPENING, EDIT_PRICES, REPORT_MEMBER_PER_YEAR
            , SHOW_MONTH_DETAILS, EDIT_HAPPENING, EDIT_PROJECTS, END_YEAR, END_MONTH, TRUST_STATUS
            , REPORT_USERS_EMAIL, EDIT_TRUST_ACTIONS, EDIT_TRUST, REPORT_ADDRESSES, REPORT_SELECTEDLINES
            , LOGOUT, EDIT_USERS, EDIT_ACCOUNTS, REPORT_LETTER, REPORT_EMAIL, REPORT_ACCOUNTTRACK
            , EDIT_ACCOUNTTRACK, BUDGET, SHOW_ALL_MEMBERS, EDIT_SEMESTER, MANAGE_FILES, REPORT_MEMBER_PER_YEAR_GENDER
            , LOGGING, BACKUP, END_SEMESTER, REPORT_YEAR, REPORT_EARNINGS_YEAR, BUDGET_SIMPLE_TRACKING
            , SERVERINFO, EDIT_EMAIL_CONTENT, EXPORT_PERSON, IMPORT_PERSON, ADMIN_INSTALLS, ADMIN_SQL, ADMIN_OPERATIONS, EXPORT_ACCOUNTING, 
            EDIT_MASSLETTER_SIMPLE, CALCULATOR;


}
