#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.3.3/gwt-user.jar:/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.3.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" no.knubo.accounting.AccountingGWT;
